# Generated by Django 5.0.1 on 2024-01-20 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_alter_quiz_end_time_alter_quiz_start_time'),
        ('student_app', '0002_remove_student_grade_group_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='group',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='student_app.grade'),
            preserve_default=False,
        ),
    ]
