# Generated by Django 5.0.1 on 2024-01-20 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_subject_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='group',
            new_name='grade',
        ),
    ]
