# Generated by Django 5.0.1 on 2024-01-20 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_rename_group_subject_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=455)),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='quizes', to='quiz_app.quiztype'),
            preserve_default=False,
        ),
    ]
