# Generated by Django 5.0.1 on 2024-01-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0006_rename_created_at_result_start_time_and_more'),
        ('student_app', '0002_remove_student_grade_group_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='groups',
            field=models.ManyToManyField(to='student_app.group'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='no_permission_students',
            field=models.ManyToManyField(to='student_app.student'),
        ),
    ]
